### ISSUE TITLE
starship is not called after install

### ISSUE THREAD

**Issue by gtujan** [relaxdiego/dotfiles#2]
Starship is not called after the installation.
Needs the following line at the end of ~/.bashrc 

`eval "$(starship init bash)"`

**Comment by relaxdiego** [comment]
It's enabled if `shared_machine = false` in `~/.config/chezmoi/chezmoi.toml` :-)

https://github.com/relaxdiego/dotfiles/blob/2f3f1cc3803a3dcd4c70cf3a173e560e675ebad8/dot_bashrc.tmpl#L145-L151
